### ISSUE TITLE
Spring/Hibernate ORM

### ISSUE THREAD

**Issue by rodrigoduterte** [rodrigoduterte/rsn#27]
- Creating the hibernate.cfg.xml not necessary for Spring. DB connection is placed on bean 
- [x] Create a JPA model
- [x] Create the pojos/beans for ORM without hibernate annotations
- [x] Populate Database with Mock Data
- [x] Add hibernate annotations for the pojos/beans
- [x] Generate database table schema
- [x] Findout how spring configures hibernate
- [x] Run a demo project
- [x] Integrate the demo project to group project
- [x] Remodel Database schema

**Comment by rodrigoduterte** [comment]
Please demo the example here @gaelgino @rodrigoduterte 
https://ashismo.github.io/java-spring/2015/05/25/Spring-ORM-Example

**Comment by rodrigoduterte** [comment]
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [spring-config.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Dialect class not found: PostgreSQL95Dialect
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)

**Comment by rodrigoduterte** [comment]
Hibernate not populating junction table. Should change Database schema and code that populates tables
![image](https://user-images.githubusercontent.com/24198006/64857332-3afd6e00-d5f2-11e9-9c4f-07ad5fa7d01e.png)

![image](https://user-images.githubusercontent.com/24198006/64857379-5bc5c380-d5f2-11e9-8688-2b7b217c5864.png)

**Comment by rodrigoduterte** [comment]
Trying to solve this after changing our schema
![image](https://user-images.githubusercontent.com/24198006/64858571-c0365200-d5f5-11e9-8500-a74d4139acc7.png)

**Comment by rodrigoduterte** [comment]
![image](https://user-images.githubusercontent.com/24198006/64859127-6d5d9a00-d5f7-11e9-956c-b5190379905f.png)

**Comment by rodrigoduterte** [comment]
Tested Hibernate Transactions rollback with jUnit for Spring DAOs 

Sep 14, 2019 6:55:46 AM org.springframework.test.context.support.AbstractTestContextBootstrapper getDefaultTestExecutionListenerClassNames
INFO: Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]
Sep 14, 2019 6:55:46 AM org.springframework.test.context.support.AbstractTestContextBootstrapper getTestExecutionListeners
INFO: Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@4bec1f0c, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@29ca901e, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@5649fd9b, org.springframework.test.context.support.DirtiesContextTestExecutionListener@6adede5, org.springframework.test.context.transaction.TransactionalTestExecutionListener@2d928643, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@5025a98f]
Sep 14, 2019 6:55:46 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [localContext.xml]
Sep 14, 2019 6:55:47 AM org.springframework.beans.factory.support.DefaultListableBeanFactory registerBeanDefinition
INFO: Overriding bean definition for bean 'profileRepo' with a different definition: replacing [Generic bean: class [com.rsn.repository.ProfileRepo]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [C:\Users\vorga\Documents\228\Spring2\target\classes\com\rsn\repository\ProfileRepo.class]] with [Generic bean: class [com.rsn.repository.ProfileRepo]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [localContext.xml]]
Sep 14, 2019 6:55:47 AM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.GenericApplicationContext@63e2203c: startup date [Sat Sep 14 06:55:47 EDT 2019]; root of context hierarchy
Sep 14, 2019 6:55:48 AM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {5.4.2.Final}
Sep 14, 2019 6:55:48 AM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
Sep 14, 2019 6:55:50 AM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.Oracle10gDialect
Sep 14, 2019 6:57:06 AM org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Sep 14, 2019 6:57:07 AM org.springframework.orm.hibernate5.HibernateTransactionManager afterPropertiesSet
INFO: Using DataSource [org.springframework.jdbc.datasource.DriverManagerDataSource@2e55dd0c] of Hibernate SessionFactory for HibernateTransactionManager
Sep 14, 2019 6:57:09 AM org.springframework.test.context.transaction.TransactionContext startTransaction
INFO: Began transaction (1) for test context [DefaultTestContext@27fe9713 testClass = TestProfileRepo, testInstance = com.rsn.test.repo.TestProfileRepo@11c3ff67, testMethod = selectAllByNameWorks@TestProfileRepo, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@4397a639 testClass = TestProfileRepo, locations = '{classpath:localContext.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]; transaction manager [org.springframework.orm.hibernate5.HibernateTransactionManager@4adc663e]; rollback [true]
Sep 14, 2019 6:57:10 AM org.springframework.test.context.transaction.TransactionContext endTransaction
INFO: Rolled back transaction for test: [DefaultTestContext@27fe9713 testClass = TestProfileRepo, testInstance = com.rsn.test.repo.TestProfileRepo@11c3ff67, testMethod = selectAllByNameWorks@TestProfileRepo, testException = java.lang.AssertionError: expected:<0> but was:<2>, mergedContextConfiguration = [MergedContextConfiguration@4397a639 testClass = TestProfileRepo, locations = '{classpath:localContext.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]
Sep 14, 2019 6:57:11 AM org.springframework.test.context.transaction.TransactionContext startTransaction
INFO: Began transaction (1) for test context [DefaultTestContext@27fe9713 testClass = TestProfileRepo, testInstance = com.rsn.test.repo.TestProfileRepo@4ed4a7e4, testMethod = getUser@TestProfileRepo, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@4397a639 testClass = TestProfileRepo, locations = '{classpath:localContext.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]; transaction manager [org.springframework.orm.hibernate5.HibernateTransactionManager@4adc663e]; rollback [true]
Sep 14, 2019 6:57:12 AM org.springframework.test.context.transaction.TransactionContext endTransaction
INFO: Rolled back transaction for test: [DefaultTestContext@27fe9713 testClass = TestProfileRepo, testInstance = com.rsn.test.repo.TestProfileRepo@4ed4a7e4, testMethod = getUser@TestProfileRepo, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@4397a639 testClass = TestProfileRepo, locations = '{classpath:localContext.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]
Sep 14, 2019 6:57:12 AM org.springframework.test.context.transaction.TransactionContext startTransaction
INFO: Began transaction (1) for test context [DefaultTestContext@27fe9713 testClass = TestProfileRepo, testInstance = com.rsn.test.repo.TestProfileRepo@619f2afc, testMethod = recordCount@TestProfileRepo, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@4397a639 testClass = TestProfileRepo, locations = '{classpath:localContext.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]; transaction manager [org.springframework.orm.hibernate5.HibernateTransactionManager@4adc663e]; rollback [true]
Sep 14, 2019 6:57:13 AM org.springframework.test.context.transaction.TransactionContext endTransaction
INFO: Rolled back transaction for test: [DefaultTestContext@27fe9713 testClass = TestProfileRepo, testInstance = com.rsn.test.repo.TestProfileRepo@619f2afc, testMethod = recordCount@TestProfileRepo, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@4397a639 testClass = TestProfileRepo, locations = '{classpath:localContext.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]]
Sep 14, 2019 6:57:13 AM org.springframework.context.support.AbstractApplicationContext doClose
INFO: Closing org.springframework.context.support.GenericApplicationContext@63e2203c: startup date [Sat Sep 14 06:55:47 EDT 2019]; root of context hierarchy
